### PR TITLE
[6268] Update sdk packages

### PR DESCRIPTION
**Pull request by jvega190**
https://github.com/craftercms/craftercms/issues/6268

- Update SDK packages
- Update dependencies
- Update yarn to v4
- Migrate from CRA to Vite

### CODE REVIEW

**Review by rart — APPROVED** [review]

**Comment by sumerjabri** [comment]
@jvega190 please pull and rebuild the code because deps were updated. (Be careful not to mess up the `yarn.lock`.)

**Comment by jvega190** [comment]
This is ready for merge and it's compatible with 4.1.2

**Review by rart — APPROVED** [review]
@sumerjabri is there a way we could test the blueprint as in from marketplace without publishing and requiring another publish if an issue is found, etc?

@jvega190 at a minimum, once merged retest by creating from remote seeing the bp run and testing the installation of the react app is successful and can also run in dev mode

**Comment by sumerjabri** [comment]
@rart create from remote. You could use @jvega190 's branch to test. Now that it's merged, you can test this. However, I'd like to merge only when things are ready, so this is an exception.

**Pull request merged**
